Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ExpressVoitures.Controllers
{
    public class AdminController : Controller
    {
        [Authorize]
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/VehiclesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExpressVoitures.Data;
using Microsoft.AspNetCore.Authorization;
using Microsoft.Extensions.Hosting;
using ExpressVoitures.Models;

namespace ExpressVoitures.Controllers
{
    public class VehiclesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _hostEnvironment;

        public VehiclesController(ApplicationDbContext context, IWebHostEnvironment hostEnvironment)
        {
            _context = context;
            _hostEnvironment = hostEnvironment;
        }

        // GET: Vehicles
        public async Task<IActionResult> Index(VehicleFilters filters)
        {
            var query = _context.Vehicles
                .Include(v => v.Finition)
                .Include(v => v.Marque)
                .Include(v => v.Modele)
                .Include(v => v.Images)
                .Where(v => v.IsPublished == true)
                .AsQueryable();

            if (filters != null)
            {
                if (filters.MarqueId.HasValue)
                {
                    query = query.Where(v => v.MarqueId == filters.MarqueId.Value);
                }

                if (filters.ModeleId.HasValue)
                {
                    query = query.Where(v => v.ModeleId == filters.ModeleId.Value);
                }

                if (filters.FinitionId.HasValue)
                {
                    query = query.Where(v => v.FinitionId == filters.FinitionId.Value);
                }

                if (filters.Annee.HasValue)
                {
                    query = query.Where(v => v.Annee == filters.Annee.Value);
                }

                if (filters.Disponible.HasValue && filters.Disponible.Value)
                {
                    query = query.Where(v => v.DateVente == null);
                }
                ViewBag.Filters = filters;
            }

            var marques = _context.Marques.ToList();
            ViewBag.Marques = marques.Select(m => new { m.Id, m.Nom }).ToList();
            ViewBag.Modeles = _context.Modeles.Select(model => new { model.Id, model.Nom, model.MarqueId }).ToList();
            ViewBag.Finitions = _context.Finitions.Select(f => new { f.Id, f.Nom, f.ModeleId }).ToList();

            ViewBag.Filters = filters;

            ViewBag.MarqueId = filters.MarqueId;
            ViewBag.ModeleId = filters.ModeleId;
            ViewBag.FinitionId = filters.FinitionId;

            var vehicles = await query.ToListAsync();
            return View(vehicles);
        }


        // GET: Vehicles/AdminIndex
        [Authorize]
        public async Task<IActionResult> AdminIndex()
        {
            var applicationDbContext = _context.Vehicles
                .Include(v => v.Finition)
                .Include(v => v.Marque)
                .Include(v => v.Modele)
                .Include(v => v.Images);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Vehicles/Listing/5
        public async Task<IActionResult> Listing(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .Include(v => v.Finition)
                .Include(v => v.Marque)
                .Include(v => v.Modele)
                .Include(v => v.Images)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Details/5
        [Authorize]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .Include(v => v.Finition)
                .Include(v => v.Marque)
                .Include(v => v.Modele)
                .Include(v => v.Images)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (vehicle == null)
            {
                return NotFound();
            }

            return View(vehicle);
        }

        // GET: Vehicles/Create
        [Authorize]
        public IActionResult Create()
        {
            var marques = _context.Marques.ToList();
            ViewBag.Marques = marques.Select(m => new { Id = m.Id, Nom = m.Nom }).ToList();
            ViewBag.Modeles = _context.Modeles.Select(model => new { Id = model.Id, Nom = model.Nom, MarqueId = model.MarqueId }).ToList();
            ViewBag.Finitions = _context.Finitions.Select(f => new { Id = f.Id, Nom = f.Nom, ModeleId = f.ModeleId }).ToList();

            return View();
        }

        // POST: Vehicles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create(Vehicle vehicle, List<IFormFile> images)
        {
            ModelState.Remove("Marque");
            ModelState.Remove("Modele");
            ModelState.Remove("Finition");
            if (ModelState.IsValid)
            {
                _context.Add(vehicle);
                await _context.SaveChangesAsync();

                // Créer le dossier pour stocker les images
                var uploadDir = Path.Combine(_hostEnvironment.WebRootPath, "img/annonces", vehicle.Id.ToString());
                if (!Directory.Exists(uploadDir))
                {
                    Directory.CreateDirectory(uploadDir);
                }

                // Sauvegarder les images
                foreach (var image in images)
                {
                    if (image != null && image.Length > 0)
                    {
                        var filePath = Path.Combine(uploadDir, image.FileName);
                        using (var stream = new FileStream(filePath, FileMode.Create))
                        {
                            await image.CopyToAsync(stream);
                        }

                        // Ajouter l'image à la base de données
                        var carImage = new CarImage
                        {
                            VehicleId = vehicle.Id,
                            ImageLink = $"/img/annonces/{vehicle.Id}/{image.FileName}"
                        };
                        _context.VehicleImages.Add(carImage);
                    }
                }

                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(AdminIndex));
            }

            // Si la validation échoue, rechargez les listes déroulantes et affichez à nouveau le formulaire avec les erreurs de validation
            var marques = _context.Marques.ToList();
            ViewBag.Marques = marques.Select(m => new { m.Id, m.Nom }).ToList();
            ViewBag.Modeles = _context.Modeles.Select(model => new { model.Id, model.Nom, model.MarqueId }).ToList();
            ViewBag.Finitions = _context.Finitions.Select(f => new { f.Id, f.Nom, f.ModeleId }).ToList();

            ViewBag.ModeleId = vehicle.ModeleId;
            ViewBag.FinitionId = vehicle.FinitionId;
            return View(vehicle);
        }


        // GET: Vehicles/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var vehicle = await _context.Vehicles
                .Include(v => v.Images)
                .FirstOrDefaultAsync(v => v.Id == id);

            if (vehicle == null)
            {
                return NotFound();
            }

            var marques = _context.Marques.ToList();
            ViewBag.Marques = marques.Select(m => new { m.Id, m.Nom }).ToList();
            ViewBag.Modeles = _context.Modeles.Select(model => new { model.Id, model.Nom,model.MarqueId }).ToList();
            ViewBag.Finitions = _context.Finitions.Select(f => new { f.Id, f.Nom, f.ModeleId }).ToList();

            ViewBag.ModeleId = vehicle.ModeleId;
            ViewBag.FinitionId = vehicle.FinitionId;
            return View(vehicle);
        }


        // POST: Vehicles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, Vehicle vehicle, List<IFormFile> images)
        {
            if (id != vehicle.Id)
            {
                return NotFound();
            }

            ModelState.Remove("Marque");
            ModelState.Remove("Modele");
            ModelState.Remove("Finition");
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(vehicle);
                    await _context.SaveChangesAsync();

                    if (images != null && images.Count > 0)
                    {
                        // Créer le dossier pour stocker les images
                        var uploadDir = Path.Combine(_hostEnvironment.WebRootPath, "img/annonces", vehicle.Id.ToString());
                        if (!Directory.Exists(uploadDir))
                        {
                            Directory.CreateDirectory(uploadDir);
                        }

                        // Sauvegarder les images
                        foreach (var image in images)
                        {
                            if (image != null && image.Length > 0)

Views/Shared/_AdminPagesTitle.cshtml
<div class="row">
    <a asp-area="" asp-controller="@ViewData["ControllerName"]" asp-action="@ViewData["ActionName"]" class="col-1 btn back-button">🔙</a>
    <h1 class="col">@ViewData["NomPage"]</h1>
</div>

Views/Shared/_DetailsNavPartial.cshtml
@model dynamic

<div>
    <a class="btn icon-link" asp-action="Details" asp-route-id="@Model.Id" title="Détails">📋</a>
    <a class="btn icon-link" asp-action="Edit" asp-route-id="@Model.Id" onclick="logIssue" title="Éditer">🖋️</a>
    <a class="btn icon-link" asp-action="Delete" asp-route-id="@Model.Id" title="Supprimer">❌</a>
</div>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpressVoitures</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/listing.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ExpressVoitures.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="/img/general/logo.png" width="62px" /></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Vehicles" asp-action="Index">Annonces</a>
                        </li>
                    </ul>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Administration</a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            <div class="navbar nav-pills">
                <span class="nav-item">&copy; 2024 - ExpressVoitures</span>
                <div class="nav-item">
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_ListingCarousel.cshtml
@model IEnumerable<ExpressVoitures.Data.Vehicle>

<div id="carouselHomepageIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        @for (int i = 0; i < Model.Count(); i++)
        {
            <li data-target="#carouselHomepageIndicators" data-slide-to="@i" class="@(i == 0 ? "active" : "")"></li>
        }
    </ol>
    <div class="carousel-inner">
        @{
            bool firstSlide = true;
            foreach (var vehicle in Model)
            {
                <div class="carousel-item @(firstSlide ? "active" : "")">
                    <a asp-controller="Vehicles" asp-action="Listing" asp-route-id="@vehicle.Id">
                        @if (vehicle.DateVente != null)
                        {
                            <div class="sold-out">
                                <h4 class="sold-out-text-semitransparent">Véhicule vendu</h4>
                            </div>
                        }
                        <img class="d-block w-100" src="@(vehicle.Images != null && vehicle.Images.Any() ? vehicle.Images.FirstOrDefault().ImageLink : "/img/general/media-unavailable.png")" alt="@vehicle.Annee @vehicle.Marque.Nom @vehicle.Modele.Nom @vehicle.Finition.Nom">
                        <div class="carousel-caption controls-background d-flex flex-row justify-content-between row m-auto">
                            <div class="w-25 mx-5">
                                <h5 class="text-start">@vehicle.Marque.Nom @vehicle.Modele.Nom @vehicle.Finition.Nom</h5>
                                <h6 class="text-start">@vehicle.Annee</h6>
                            </div>
                            <div class="w-25 mx-5">
                                <h5 class="text-end">@vehicle.PrixVente €</h5>
                            </div>
                        </div>
                    </a>
                </div>
                firstSlide = false;
            }
        }
    </div>
    <a class="carousel-control-prev" href="#carouselHomepageIndicators" role="button" data-slide="prev">
        <div class="carousel-controls">
            <span class="carousel-control-prev-icon " aria-hidden="true"></span>
        </div>
    </a>
    <a class="carousel-control-next" href="#carouselHomepageIndicators" role="button" data-slide="next">
        <div class="carousel-controls">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
        </div>
    </a>
</div>

Views/Shared/_VehicleSelectPartial.cshtml
@model ExpressVoitures.Data.Vehicle

<div class="form-group">
    <label class="control-label">Marque</label>
    <select id="marqueSelect" asp-for="MarqueId" class="form-control" onchange="updateModeleSelect()">
        <option value="">Sélectionner une marque</option>
        @foreach (var marque in ViewBag.Marques)
        {
            <option value="@marque.Id">@marque.Nom</option>
        }
    </select>
    <span asp-validation-for="MarqueId" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Modele" class="control-label"></label>
    <select id="modeleSelect" asp-for="ModeleId" class="form-control" onchange="updateFinitionSelect()" disabled>
        <option value="">Sélectionner un modèle</option>
    </select>
    <span asp-validation-for="ModeleId" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Finition" class="control-label"></label>
    <select id="finitionSelect" asp-for="FinitionId" class="form-control" disabled>
        <option value="">Sélectionner une finition</option>
    </select>
    <span asp-validation-for="FinitionId" class="text-danger"></span>
</div>